name: X-Gorn/MangaLoader CI

on:
  workflow_dispatch:

env:
  APP_ID: ${{ secrets.APP_ID }}
  API_HASH: ${{ secrets.API_HASH }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  OWNER_ID: ${{ secrets.OWNER_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: 'X-Gorn/MangaLoader'
          path: 'app'

      - name: Complete Script
        timeout-minutes: 350
        continue-on-error: true
        run: |
          cd $GITHUB_WORKSPACE/app
          python3 -m pip install -r requirements.txt
          python3 bot.py
